### ISSUE TITLE
용량 최적화되지 않은 폰트 지원

### ISSUE THREAD

**Issue by cog25** [sunn-us/SUIT#1]
일부 환경에서는 완성형 2,350자와 현대 한국어 표시를 위해 제안된 224자를 제외한 글자가 필요할 수 있습니다.

이에 따라, 용량 최적화된 글꼴 외에도 모든 글자가 포함된 추가 글꼴을 배포해주시기 요청합니다.

**Comment by sunn-us** [comment]
본고딕에 포함되어 있는 모든 글자를 포함시키는 것이 어려운 일은 아니나,
SUIT는 .apk같은 패키지에 포함되는 것을 전제로 제작 되었으므로 전체 글자를 지원하는 헤비한 파일을 추가로 제작 할 예정이 현재는 없습니다.

하지만 특정 목적을 위해 제작 될 수도 있으니 추후 F/u하도록 본 이슈는 오픈 된 상태로 남겨두도록 하겠습니다.

**Comment by yookhun** [comment]
![화면 캡처 2022-04-20 181431](https://user-images.githubusercontent.com/104065316/164194624-e30115f8-8f82-4ed8-8d6b-cd839795eaa5.png)

문장을 작성하는 과정에서 지원되지 않는 글자가 지나갈 경우 포토샵, 일러 등의 어도비 프로그램에서 글씨체가 굴림으로0 바뀌는 오류가 일어납니다 ㅠㅠ
