### ISSUE TITLE
아웃라인 처리 시 깨짐 현상

### ISSUE THREAD

**Issue by MandyPark** [sunn-us/SUIT#2]
안녕하세요.
어도비 일러스트레이터에서 SUIT SemiBold 폰트의 'm' 글자가 아웃라인 처리 시 깨지는 현상이 있습니다.
폰트 파일이깨져서 그런걸까요? 다른 굵기, 글자는 괜찮은데 SemiBold의 m자만 그러네요.
사용하고있는 일러스트레이터 버전은 26.0.2 최신버전입니다.
![문의](https://user-images.githubusercontent.com/44991391/168702312-7e6a342a-c398-4c6a-9c47-1aa9801daaaf.jpg)

**Comment by sunn-us** [comment]
안녕하세요. 
방금 SUIT OTF와 일러스트레이터 버전 26.2.1에서 확인해보니 말씀 주신 현상이 재현되지 않는데,
OTF 최신 버전으로 다시 한번 확인 부탁드립니다 :-)

<img width="400" alt="Screen Shot 2022-05-17 at 10 48 33 AM" src="https://user-images.githubusercontent.com/63042729/168711960-41700ca7-f5d5-402d-b11b-d4574264db95.png">
