### ISSUE TITLE
웹폰트에서 Chromium의 버그로 local()이 포함되어 있는 경우 폰트가 정상 렌더되지 않는 문제

### ISSUE THREAD

**Issue by kms0219kms** [sunn-us/SUIT#7]
[orioncactus/pretendard#141](https://github.com/orioncactus/pretendard/discussions/141) 에서도 언급된 바와 같이 

현재 배포되는 CSS 파일에는 local() 함수를 이용하여 글꼴 로딩을 향상하기 위한 내용이 적용되어 있는 것으로 보이는데요.

Chromium 114 이후 환경(Chrome, Edge, Whale도 사용함)에서 Variable TTF 파일 설치된 상태로 확인해보니
Chrome 버그로 인하여 로컬에서 글꼴을 읽어올 수 있으면 글꼴 굵기 옵션이 무시되는 현상을 확인하였습니다.

* Firefox 브라우저에서는 어떤 옵션이어도 잘 작동합니다.

따라서 local이 제외된 css를 제공해 주실 수 있는지 여쭤보고 싶습니다.

감사합니다.

**Comment by sunn-us** [comment]
안녕하세요. 

local을 삭제하게 되면 무조건 폰트를 내려 받게 되어
Chromium의 버그가 수정되어 정상 작동되도록 기다리는 것이 맞다고 생각합니다만.
말씀 주신 이슈외의 다른 이슈도 있어 일단 local을 제외한 파일로 새롭게 릴리즈 하였고 당분간 없는 상태로 유지하려고 합니다.

이슈 등록해주셔서 감사드립니다. :-)

**Comment by kms0219kms** [comment]
@sunn-us 2.0.1에서 너무 과하게 local()이 제거된 듯합니다.
자세히 확인해 보니 가변 폰트에서만 발생하고 있는 문제라, Variable이 아닌 일반 static 형태 webfont에 대해서는 local()이 존재하는게 나아 보입니다.
