### ISSUE TITLE
라틴 알파벳 소문자 `t` 글리프 모양 변경에 대해

### ISSUE THREAD

**Issue by devunt** [sunn-us/SUIT#8]
<img width="1112" alt="image" src="https://github.com/sunn-us/SUIT/assets/337728/d3683859-cda2-400d-86fb-655bedd72a80">

안녕하세요, SUIT 폰트를 프로덕트에 늘 잘 이용하고 있습니다.
이번에 메이저 버전이 1에서 2로 올라가면서 여러 breaking change가 생긴 것 같은데요, 체감되는 가장 큰 차이중 하나가 라틴 알파벳 소문자 `t` (`U+0074`)의 글리프 모양 변경인 듯 싶습니다.

2.0.1 릴리즈 노트가 먼저 올라오고 아직 2.0.0 릴리즈 노트가 올라오지 않은 탓인지 처음 폰트를 업데이트한 뒤 예상치 못한 변경을 확인하고 살짝 당황했는데요, 혹시 이 변경에 대한 배경 히스토리가 있다면 간단히 설명을 부탁드려도 될까요?

타이포그래피를 깊게 공부해본 적이 없는 비전문자의 시각에서는 이전 버전의 `t` 글리프가 더 지오매트릭한 폰트 분위기에 어울려 보인다는 생각이 드는데, sunn님의 시각 또한 궁금합니다 👀

**Comment by sunn-us** [comment]
안녕하세요! 먼저 SUIT를 잘 사용해주셔서 감사드립니다.

지오메트릭 서체는 다른 스타일 대비 글자 크기가 크기 때문에 주로 제목 서체로 소비되고,
본문 서체로는 잘 사용하지 않습니다만 한국어로 제공되는 프로덕트에서 영문자는 주로 단위 표기나 약자 등으로 4글자 이내로 사용된다는 점에서 SUIT는 제작 당시 Gotham 같은 류의 좌우가 넓은 지오메트릭 스타일을 지향했습니다.

하지만 실제 사용되는 패턴을 살펴본 결과 제 생각보다 한국어 문장에서 긴 영문 표기를 섞어쓰는 경우가 많았고, 표기되는 글자수가 늘어날 수록 지오메트릭 폰트 특성상 한국어 대비 너무 큰 공간을 차지하게 되었습니다.

말씀 주신대로 버전2에서의 큰 변화는,
위의 문제를 해결하기 위해서 폭이 과하게 넓었던 대문자 B, D, E, M, W, X등의 폭을 줄이고, 소문자 전체의 x-Height를 대폭 낮춤으로써 지오메트릭이지만 본문 서체로의 기능성을 먼저 고려하여 메이저 업데이트를 하게 되었습니다. 이 과정에서 작아진 소문자의 가독성 확보를 위해 t의 디자인이 간소화하게 되었습니다.

의견 주셔서 감사드립니다! 🤩 

- 기존 버전을 원하시는 분이 있을수도 있어서, 공식 웹사이트에서는 v1.2.5의 다운로드 링크를 별도로 제공하고 있습니다.
- 2.0.0을 어제 릴리즈했다가, 파일이 잘못 구성되어 삭제하고 2.0.1의 마이너 업데이트를 했습니다.

**Comment by sunn-us** [comment]
릴리즈 노트에 내용을 좀 더 추가하였습니다. :-)
https://github.com/sunn-us/SUIT/releases/tag/v2.0.1

**Comment by devunt** [comment]
말씀주신 내용을 떠올리면서 새로 올려주신 비교 스크린샷을 보니 확실히 한글과 영문이 섞여있을 때는 버전 2가 조금 더 일관성 있고 조화로운 느낌이 드네요! 좋은 변경인 것 같습니다.

> 지오메트릭 서체는 다른 스타일 대비 글자 크기가 크기 때문에 주로 제목 서체로 소비되고,
본문 서체로는 잘 사용하지 않습니다만 

저희의 경우에는 SUIT를 헤드라인과 본문, 한글과 영문 가릴 것 없이 사이트 전체에서 공통적으로 쓰고 있는데요, 혹시 권장되지 않는 방식일까요?

(좌: v1.2.5, 우: v2.0.1)
<img width="960" alt="Untitled-1" src="https://github.com/sunn-us/SUIT/assets/337728/499d04d0-81a7-4316-b9ab-97d2fcd31a71">

위 이미지와 같이 v2로 바뀌면서 특히 영어가 많이 쓰이는 부분(URL 등)의 느낌이 많이 달라졌는데 좌측에 눈이 익숙해진 탓인지 우측이 조금 어색한 느낌이 들기도 합니다. 이런 경우에는 계속 버전 1을 쓰는게 좋을지, 혹은 추천하시는 다른 해결법이 있을지, 혹은 제 느낌과는 달리 변경된 우측(버전2)이 실제로는 UI적으로 더 나은 것인지 여쭙니다.

**Comment by sunn-us** [comment]
지오메트릭 서체가 제목용으로 주로 소비된다는 것은 영어권에서의 예시였습니다. 한국어 환경에서는 여러가지 이유로 웹/앱에서 제목과 본문용 서체를 별도로 나눠서 쓰는 경우는 잘 없고 주로 하나로 사용합니다.

아래 문의주신 것은 제가 보기엔 v2로 가는 것이 맞다고 생각하는데, 보시기에 큰 글자쪽이 나아 보이신다면 그대로 v1으로 사용하셔도 되지 않을까 싶습니다. 감사합니다!

**Comment by devunt** [comment]
답변 감사드립니다! 궁금했던 점들이 모두 이해되었습니다.
좋은 폰트 만들어주셔서 감사드리며 앞으로도 계속 응원하겠습니다 💪
